"use client";
import Link from "next/link";import{useEffect,useState}from"react";
const money=(v:any)=>`₦${(Number(v)/100).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})}`,date=(v:string)=>new Date(v).toLocaleString();
const tabs=[["overview","Overview"],["reconciliation","Reconciliation"],["deposits","Wallet deposits"],["orders","Orders"],["ledger","Wallet ledger"],["users","Users"]];
export default function AdminPage(){const[tab,setTab]=useState("overview"),[data,setData]=useState<any>(),[msg,setMsg]=useState("Loading…"),[search,setSearch]=useState(""),[filter,setFilter]=useState(""),[page,setPage]=useState(1);
async function load(t=tab,p=page){setMsg("Loading…");const q=new URLSearchParams({section:t,page:String(p),take:"30"});if(search)q.set("search",search);if(filter)q.set("status",filter);const r=await fetch("/api/admin/operations?"+q),b=await r.json();if(r.status===403){setData(null);setMsg("Admin access required.");return}if(!r.ok){setMsg(b.error||"Unable to load");return}setData(b);setMsg("")}
useEffect(()=>{load("overview",1)},[]);useEffect(()=>{if(tab!=="overview")load(tab,1)},[tab]);
function tabTo(t:string){setTab(t);setPage(1);setSearch("");setFilter("")}
return <main className="shell admin-shell"><header className="top"><div><b>CLOUDMART ADMIN</b><span>Wallet & operations control center</span></div><Link className="button" href="/dashboard">Customer app</Link></header><nav className="admin-tabs">{tabs.map(([id,label])=><button className={tab===id?"active":""} key={id} onClick={()=>tabTo(id)}>{label}</button>)}</nav>{msg&&<div className="notice">{msg}{msg==="Admin access required."&&<p><Link href="/admin/login">Open admin sign in →</Link></p>}</div>}{data&&tab==="overview"&&<Overview data={data}/>} {data&&tab!=="overview"&&<section className="card"><div className="admin-toolbar"><div><h2>{tabs.find(x=>x[0]===tab)?.[1]}</h2><small>{data.total??0} records</small></div><div className="toolbar-controls"><input placeholder="Search email, reference, ID…" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(tab,1)}/>{(tab==="deposits"||tab==="orders")&&<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);setTimeout(()=>load(tab,1),0)}}><option value="">All statuses</option>{(tab==="deposits"?["PENDING","CREDITED","FAILED"]:["PENDING","PROCESSING","COMPLETED","FAILED","REFUNDED","CANCELLED"]).map(x=><option key={x}>{x}</option>)}</select>}<button onClick={()=>load(tab,page)}>Refresh</button></div></div>{tab==="reconciliation"&&<Reconciliation rows={data.rows}/>} {tab==="deposits"&&<Deposits rows={data.rows}/>} {tab==="orders"&&<Orders rows={data.rows}/>} {tab==="ledger"&&<Ledger rows={data.rows}/>} {tab==="users"&&<Users rows={data.rows}/>}<Pager page={data.page} total={data.total} take={data.take} onChange={(p:number)=>{setPage(p);load(tab,p)}}/></section>}</main>}
function Overview({data}:any){return <><section className="grid admin-metrics">{Object.entries(data.metrics).map(([k,v])=><div className="card" key={k}><small>{k}</small><h1>{String(v)}</h1><p>Live database count</p></div>)}</section><div className="admin-two"><section className="card"><h2>Recent deposits</h2>{data.recentDeposits.map((x:any)=><div className="order" key={x.id}><div><b>{money(x.amountMinor)}</b><small>{x.reference} · {x.user.email}</small></div><span className={"status "+x.status.toLowerCase()}>{x.status}</span></div>)}</section><section className="card"><h2>Recent orders</h2>{data.recentOrders.map((x:any)=><div className="order" key={x.id}><div><b>{x.service.name}</b><small>{x.user.email} · {money(x.amountMinor)}</small></div><span className={"status "+x.status.toLowerCase()}>{x.status}</span></div>)}</section></div></>}
function Deposits({rows}:any){return <Table><thead><tr><th>Reference</th><th>Customer</th><th>Amount</th><th>Provider</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td><b>{x.reference}</b><small>{x.providerReference||"Awaiting provider reference"}</small></td><td>{x.user.email}</td><td>{money(x.amountMinor)} {x.currency}</td><td>{x.paymentProvider||"—"}</td><td><Status v={x.status}/></td><td>{date(x.createdAt)}</td></tr>)}</tbody></Table>}
function Orders({rows}:any){return <Table><thead><tr><th>Order</th><th>Customer</th><th>Service</th><th>Amount</th><th>Provider ref</th><th>Status</th><th>Updated</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td><Link href={"/admin/orders/"+x.id}><b>{x.id}</b></Link><small>{x.provider}</small></td><td>{x.user.email}</td><td>{x.service.name}<small>{x.service.category}</small></td><td>{money(x.amountMinor)} {x.currency}</td><td>{x.providerOrderId||"—"}</td><td><Status v={x.status}/></td><td>{date(x.updatedAt)}</td></tr>)}</tbody></Table>}
function Ledger({rows}:any){return <Table><thead><tr><th>Reference</th><th>Customer</th><th>Type</th><th>Amount</th><th>Description</th><th>Created</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td>{x.reference}</td><td>{x.user.email}</td><td><Status v={x.type}/></td><td>{money(x.amountMinor)} {x.currency}</td><td>{x.description}</td><td>{date(x.createdAt)}</td></tr>)}</tbody></Table>}
function Users({rows}:any){return <Table><thead><tr><th>Customer</th><th>Role</th><th>Wallet</th><th>Orders</th><th>Deposits</th><th>Joined</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td><b>{x.email}</b><small>{x.name||"No name"}</small></td><td>{x.role}</td><td>{money(x.wallet?.balanceMinor||"0")} {x.wallet?.currency||"NGN"}</td><td>{x._count.orders}</td><td>{x._count.deposits}</td><td>{date(x.createdAt)}</td></tr>)}</tbody></Table>}
function Table({children}:any){return <div className="table-wrap"><table>{children}</table></div>}function Status({v}:{v:string}){return <span className={"status "+v.toLowerCase()}>{v}</span>}function Pager({page,total,take,onChange}:any){const pages=Math.max(1,Math.ceil(total/take));return <div className="pager"><span>Page {page} of {pages}</span><div><button disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</button><button disabled={page>=pages} onClick={()=>onChange(page+1)}>Next</button></div></div>}
function Reconciliation({rows}:any){return <Table><thead><tr><th>Order</th><th>Customer</th><th>Service</th><th>Provider</th><th>Reconciliation reason</th><th>Age</th><th>Created</th><th></th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td><Link href={"/admin/orders/"+x.id}><b>{x.id}</b></Link></td><td>{x.user.email}</td><td>{x.service.name}<small>{x.service.category}</small></td><td>{x.providerOrderId||"Awaiting provider ref"}</td><td><Status v={x.stale?"STALE":"AMBIGUOUS"}/></td><td>{x.ageMinutes} min</td><td>{date(x.createdAt)}</td><td><Link className="button" href={"/admin/orders/"+x.id}>Review →</Link></td></tr>)}</tbody></Table>}
