"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
type Service={slug:string;name:string;category?:string;requiredFields?:string[];pricing:{providerAmount:string;providerCurrency:string;sellMinor:string}|null};
const label=(v:string)=>v.replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const price=(s:Service)=>s.pricing?"₦"+(Number(s.pricing.sellMinor)/100).toLocaleString("en-NG",{minimumFractionDigits:2}):"Pricing unavailable";
export default function CatalogBrowser({initialCategory=""}:{initialCategory?:string}){
 const[services,setServices]=useState<Service[]>([]),[query,setQuery]=useState(""),[category,setCategory]=useState(initialCategory),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/services",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load catalog");setServices(b.services||[])}).catch(e=>setError(e instanceof Error?e.message:"Unable to load catalog")).finally(()=>setLoading(false))},[]);
 const categories=useMemo(()=>Array.from(new Set(services.map(s=>s.category).filter(Boolean) as string[])).sort(),[services]);
 const filtered=useMemo(()=>services.filter(s=>(!category||s.category===category)&&(!query||[s.name,s.category||"",s.slug].join(" ").toLowerCase().includes(query.toLowerCase()))),[services,category,query]);
 return <main className="catalog-page"><nav className="catalog-nav"><Link href="/" className="catalog-brand"><span>C</span>CLOUDMART</Link><div><Link href="/login">Sign in</Link><Link href="/dashboard" className="catalog-nav-button">Account →</Link></div></nav>
 <header className="catalog-hero"><span className="section-kicker">LIVE MARKETPLACE</span><h1>Choose what<br/><em>you need.</em></h1><p>Browse CloudMart's live digital services and see current selling prices before checkout.</p></header>
 <section className="catalog-controls"><div className="catalog-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search services..." aria-label="Search services"/></div><div className="category-scroll"><button className={!category?"selected":""} onClick={()=>setCategory("")}>All</button>{categories.map(c=><button key={c} className={category===c?"selected":""} onClick={()=>setCategory(c)}>{label(c)}</button>)}</div></section>
 {loading?<div className="catalog-state">Loading live catalog…</div>:error?<div className="catalog-state error-box"><strong>Catalog unavailable</strong><p>{error}</p><button onClick={()=>location.reload()}>Try again</button></div>:<><div className="catalog-meta"><strong>{filtered.length}</strong> service{filtered.length===1?"":"s"}{category&&<> in <b>{label(category)}</b></>}</div>{filtered.length?<div className="catalog-grid">{filtered.map((s,i)=><article className="catalog-card" key={s.slug}><div className="catalog-card-top"><span className="catalog-icon">{String(i+1).padStart(2,"0")}</span><span className="catalog-category">{label(s.category||"Digital")}</span></div><h2>{s.name}</h2><p>{s.requiredFields?.length?s.requiredFields.length+" detail"+(s.requiredFields.length===1?"":"s")+" required at checkout.":"Ready for secure checkout."}</p><div className="catalog-card-bottom"><strong>{price(s)}</strong><Link href={"/services/"+encodeURIComponent(s.slug)}>View service <span>→</span></Link></div></article>)}</div>:<div className="catalog-state"><strong>No services found.</strong><p>Try another search or category.</p><button onClick={()=>{setQuery("");setCategory("")}}>Clear filters</button></div>}</>}</main>;
}